"""Add name column to Room model

Revision ID: 7a77c18180a8
Revises: 
Create Date: 2024-10-09 14:58:30.219198

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a77c18180a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complex_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rooms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('room_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('depth', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('doors', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('coolers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('usage', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('materials', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.alter_column('partitions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.drop_column('length')
        batch_op.drop_column('cooler_type')
        batch_op.drop_column('door_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('door_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cooler_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('length', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.alter_column('partitions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.drop_column('materials')
        batch_op.drop_column('usage')
        batch_op.drop_column('coolers')
        batch_op.drop_column('doors')
        batch_op.drop_column('depth')
        batch_op.drop_column('room_type')
        batch_op.drop_column('name')

    op.drop_table('complex_room')
    # ### end Alembic commands ###
