"""empty message

Revision ID: e86b76b46178
Revises: 
Create Date: 2024-10-16 15:40:41.680939

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e86b76b46178'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complex_room', schema=None) as batch_op:
        batch_op.alter_column('rooms',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('features', sa.PickleType(), nullable=True))
        batch_op.add_column(sa.Column('exterior_filename', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('interior_filename', sa.String(length=200), nullable=True))
        batch_op.drop_column('coolers')
        batch_op.drop_column('materials')
        batch_op.drop_column('usage')
        batch_op.drop_column('partitions')
        batch_op.drop_column('doors')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doors', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('partitions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('usage', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('materials', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('coolers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('interior_filename')
        batch_op.drop_column('exterior_filename')
        batch_op.drop_column('features')

    with op.batch_alter_table('complex_room', schema=None) as batch_op:
        batch_op.alter_column('rooms',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    # ### end Alembic commands ###
